openapi: 3.0.0
info:
  title: Dream Sink API
  version: v1
servers:
  - url: http://localhost:5000
tags: 
  - name: dreams
    description: 夢に関するAPI
  - name: auth
    description: 認証に関するAPI
paths:
  /login:
    post: 
      tags:
        - auth
      summary: Login
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '401':
          description: Unauthorized

  /dreams/mine:
    get:
      tags: 
        - dreams
      summary: Get my dreams
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dream'
    post:
      tags: 
        - dreams
      summary: Create a new dream
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                is_public:
                  type: boolean
              required:
                - content
                - is_public
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dream'
        '400':
          description: BadRequest

  /dreams/mine/{dream_id}:
    delete:
      tags:
        - dreams
      summary: Delete my dream
      security:
        - BearerAuth: []
      parameters:
        - name: dream_id
          in: path
          required: true
          schema:
            type: string
            format: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found

  /dreams/public:
    get:
      tags:
        - dreams
      summary: Get public dreams
      operationId: getPublicDreams
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dream'
  /dreams/public/{dream_id}:
    patch:
      tags:
        - dreams
      summary: Increment public dream likes
      security: []
      parameters:
        - name: dream_id
          in: path
          required: true
          schema:
            type: string
            format: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dream'

components:
  schemas:
    Dream:
      type: object
      properties:
        id:
          type: string
          format: integer
        user_id:
          type: string
          format: integer
        content:
          type: string
          format: date
        is_public:
          type: boolean
        likes:
          type: integer
          minimum: 0
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: string
          format: integer
        name:
          type: string
        email:
          type: string
          format: email

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
