openapi: 3.0.0
info:
  title: Dream Sink API
  version: v1
servers:
  - url: https://dreamsink-backend.onrender.com
tags: 
  - name: dreams
    description: 夢に関するAPI
  - name: users
    description: ユーザーに関するAPI
  - name: auth
    description: 認証に関するAPI
paths:
  /login:
    post:
      tags:
        - auth
      summary: ログイン
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
        '401':
          description: Unauthorized

  /dreams/mine:
    get:
      tags: 
        - dreams
      summary: 自分の夢を取得する
      operationId: getMyDreams
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dream'
        '401':
          description: Unauthorized

    post:
      tags: 
        - dreams
      summary: 自分の夢を投稿する
      operationId: createMyDream
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                is_public:
                  type: boolean
              required:
                - content
                - is_public
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dream'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

  /dreams/mine/{dream_id}:
    patch: 
      tags:
        - dreams
      summary: 自分の夢を公開 or 非公開する
      operationId: toggleMyDreamVisibility
      security: 
        -  BearerAuth: []
      parameters:
        - name: dream_id
          in: path
          required: true
          schema:
            type: string
            format: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dream'
        '401':
          description: Unauthorized
        '404':
          description: Not Found

    delete:
      tags:
        - dreams
      summary: 自分の夢を削除する
      operationId: deleteMyDream
      security:
        - BearerAuth: []
      parameters:
        - name: dream_id
          in: path
          required: true
          schema:
            type: string
            format: integer
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '404':
          description: Not Found

  /dreams/public:
    get:
      tags:
        - dreams
      summary: 公開されている夢を取得する
      operationId: getPublicDreams
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dream'

  /dreams/public/{dream_id}:
    patch:
      tags:
        - dreams
      summary: 公開されている夢のいいね数を増やす
      operationId: incrementPublicDreamLikes
      security: []
      parameters:
        - name: dream_id
          in: path
          required: true
          schema:
            type: string
            format: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dream'
        '404':
          description: Not Found

  /users:
    post: 
      tags: 
        -  users
      summary: ユーザーを作成する
      operationId: createUser
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
        '400':
          description: Bad Request
        '409':
          description: Conflict
        '500':
          description: Internal Server Error

components:
  schemas:
    Dream:
      type: object
      properties:
        id:
          type: string
          format: integer
        user_id:
          type: string
          format: uuid
        content:
          type: string
          format: date
        is_public:
          type: boolean
        likes:
          type: integer
          minimum: 0
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        password_hash:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
